"""
CAD file parser — supports STL/OBJ via trimesh (mock_cad_mode=True)
and STEP/IGES via pythonocc-core (mock_cad_mode=False).
Returns a unified GeometryData object.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np
import structlog

from app.config import settings

logger = structlog.get_logger(__name__)


@dataclass
class GeometryData:
    """Unified geometry representation from any supported CAD format."""
    volume: float = 0.0              # mm³
    surface_area: float = 0.0        # mm²
    bbox: Tuple[float, float, float] = (0.0, 0.0, 0.0)  # (dx, dy, dz) in mm
    center_of_mass: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    vertices: Optional[np.ndarray] = field(default=None, repr=False)   # (N,3) float32
    faces: Optional[np.ndarray]   = field(default=None, repr=False)    # (M,3) int32
    normals: Optional[np.ndarray] = field(default=None, repr=False)    # (M,3) float32
    # Feature hints populated during parsing
    is_watertight: bool = False
    num_components: int = 1
    format: str = "unknown"


async def parse_cad_file(file_path: Path, deflection: float = 5.0) -> GeometryData:
    """
    Parse a CAD file and return structured geometry data.
    Dispatches to the appropriate parser based on file extension and mode.
    """
    suffix = file_path.suffix.lower()
    logger.info("Parsing CAD file", path=str(file_path), format=suffix, mock=settings.mock_cad_mode, deflection=deflection)

    if suffix in (".stl", ".obj", ".ply"):
        return await _parse_mesh_file(file_path, suffix, deflection)
    elif suffix in (".step", ".stp", ".iges", ".igs"):
        if suffix in (".step", ".stp"):
            try:
                import cascadio
                return await _parse_step_cascadio(file_path, suffix, deflection)
            except Exception as e:
                logger.warning("cascadio parsing failed or not available, falling back to other methods", error=str(e), exc_info=True)

        if settings.mock_cad_mode:
            logger.warning("Mock CAD mode: STEP/IGES parsed as synthetic geometry")
            return _synthetic_geometry(suffix, deflection, file_path)
        else:
            return await _parse_step_iges(file_path, suffix, deflection)
    else:
        raise ValueError(f"Unsupported CAD format: {suffix}")


async def _parse_step_cascadio(file_path: Path, suffix: str, deflection: float = 5.0) -> GeometryData:
    """
    Parse STEP file using cascadio wrapper for OpenCASCADE.
    Converts STEP to GLB and loads via trimesh, returning precise triangulated geometry.
    """
    import cascadio
    import trimesh
    import tempfile

    logger.info("Parsing STEP file using cascadio", path=str(file_path), deflection=deflection)

    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            glb_path = Path(tmpdir) / f"{file_path.stem}.glb"
            # Map deflection (in mm) to linear tolerance (in meters) for OpenCASCADE mesher
            tol_linear = max(0.0001, deflection / 1000.0)
            
            cascadio.step_to_glb(
                str(file_path),
                str(glb_path),
                tol_linear=tol_linear,
                tol_angular=0.5,
                tol_relative=False,
                merge_primitives=True,
                use_parallel=True
            )
            
            if not glb_path.exists():
                raise FileNotFoundError("GLB file was not generated by cascadio")
                
            mesh = trimesh.load(str(glb_path), force="mesh")
            
        if isinstance(mesh, trimesh.Scene):
            mesh = trimesh.util.concatenate(mesh.geometry.values())
            
        # Scale from meters to millimeters (glTF specifies coordinates in meters)
        mesh.apply_scale(1000.0)
        
        bbox_extent = mesh.bounding_box.extents
        volume = float(mesh.volume)
        if math.isnan(volume) or volume <= 0.0 or volume < (mesh.convex_hull.volume * 0.001):
            volume = float(mesh.convex_hull.volume)
        else:
            volume = abs(volume)
            
        surface_area = float(mesh.area)
        com = mesh.center_mass.tolist()
        
        try:
            num_components = len(mesh.split()) if hasattr(mesh, 'split') else 1
        except Exception:
            num_components = 1
            
        return GeometryData(
            volume=volume,
            surface_area=surface_area,
            bbox=(float(bbox_extent[0]), float(bbox_extent[1]), float(bbox_extent[2])),
            center_of_mass=(float(com[0]), float(com[1]), float(com[2])),
            vertices=np.array(mesh.vertices, dtype=np.float32),
            faces=np.array(mesh.faces, dtype=np.int32),
            normals=np.array(mesh.face_normals, dtype=np.float32) if hasattr(mesh, 'face_normals') else None,
            is_watertight=bool(mesh.is_watertight),
            num_components=num_components,
            format=suffix.lstrip("."),
        )
    except Exception as e:
        logger.error("cascadio parsing failed", error=str(e), exc_info=True)
        raise e



async def _parse_mesh_file(file_path: Path, suffix: str, deflection: float = 5.0) -> GeometryData:
    """Parse STL or OBJ using trimesh (runs on Windows natively)."""
    import trimesh

    mesh = trimesh.load(str(file_path), force="mesh")

    if isinstance(mesh, trimesh.Scene):
        mesh = trimesh.util.concatenate(mesh.geometry.values())

    # Scale detection: if bounding box suggests metres, convert to mm
    bbox_extent = mesh.bounding_box.extents  # (dx, dy, dz)
    if max(bbox_extent) < 0.1:
        # Likely in metres, scale to mm
        mesh.apply_scale(1000.0)
        bbox_extent = mesh.bounding_box.extents

    volume = float(mesh.volume) if mesh.is_watertight else float(mesh.convex_hull.volume)
    surface_area = float(mesh.area)
    com = mesh.center_mass.tolist()

    try:
        num_components = len(mesh.split()) if hasattr(mesh, 'split') else 1
    except Exception:
        num_components = 1

    return GeometryData(
        volume=volume,
        surface_area=surface_area,
        bbox=(float(bbox_extent[0]), float(bbox_extent[1]), float(bbox_extent[2])),
        center_of_mass=(float(com[0]), float(com[1]), float(com[2])),
        vertices=np.array(mesh.vertices, dtype=np.float32),
        faces=np.array(mesh.faces, dtype=np.int32),
        normals=np.array(mesh.face_normals, dtype=np.float32),
        is_watertight=bool(mesh.is_watertight),
        num_components=num_components,
        format=suffix.lstrip("."),
    )


async def _parse_step_iges(file_path: Path, suffix: str, deflection: float = 0.5) -> GeometryData:
    """
    Parse STEP/IGES using pythonocc-core (OpenCASCADE).
    Only available in Docker environment.
    """
    try:
        from OCC.Core.BRep import BRep_Builder
        from OCC.Core.BRepBndLib import brepbndlib
        from OCC.Core.BRepGProp import brepgprop
        from OCC.Core.Bnd import Bnd_Box
        from OCC.Core.GProp import GProp_GProps
        from OCC.Core.STEPControl import STEPControl_Reader
        from OCC.Core.IGESControl import IGESControl_Reader
        from OCC.Core.BRepMesh import BRepMesh_IncrementalMesh
        from OCC.Core.TopExp import TopExp_Explorer
        from OCC.Core.TopAbs import TopAbs_FACE
        from OCC.Extend.DataExchange import read_step_file, read_iges_file

        if suffix in (".step", ".stp"):
            shape = read_step_file(str(file_path))
        else:
            shape = read_iges_file(str(file_path))

        # Compute mass properties
        props = GProp_GProps()
        brepgprop.VolumeProperties(shape, props)
        volume = props.Mass()  # mm³ (assuming mm units)
        com_pt = props.CentreOfMass()

        brepgprop.SurfaceProperties(shape, props)
        surface_area = props.Mass()

        # Bounding box
        bbox = Bnd_Box()
        brepbndlib.Add(shape, bbox)
        xmin, ymin, zmin, xmax, ymax, zmax = bbox.Get()

        # Tessellate for viewer - deflection parameter dictates element size/refinement
        BRepMesh_IncrementalMesh(shape, deflection, False, 0.5, True)
        vertices, faces = _extract_occ_mesh(shape)

        return GeometryData(
            volume=abs(volume),
            surface_area=abs(surface_area),
            bbox=(abs(xmax - xmin), abs(ymax - ymin), abs(zmax - zmin)),
            center_of_mass=(com_pt.X(), com_pt.Y(), com_pt.Z()),
            vertices=vertices,
            faces=faces,
            is_watertight=True,
            format=suffix.lstrip("."),
        )
    except ImportError:
        logger.error("pythonocc-core not available; falling back to synthetic geometry")
        return _synthetic_geometry(suffix, deflection, file_path)


def _extract_occ_mesh(shape) -> Tuple[np.ndarray, np.ndarray]:
    """Extract tessellated mesh from an OCC BRep shape."""
    from OCC.Core.BRep import BRep_Tool
    from OCC.Core.BRepMesh import BRepMesh_IncrementalMesh
    from OCC.Core.TopExp import TopExp_Explorer
    from OCC.Core.TopAbs import TopAbs_FACE
    from OCC.Core.TopoDS import topods

    explorer = TopExp_Explorer(shape, TopAbs_FACE)
    all_verts, all_faces = [], []
    offset = 0

    while explorer.More():
        face = topods.Face(explorer.Current())
        triangulation = BRep_Tool.Triangulation_s(face, face.Location())
        if triangulation is not None:
            nodes = triangulation.Nodes()
            tris = triangulation.Triangles()
            verts = np.array([[nodes.Value(i + 1).X(), nodes.Value(i + 1).Y(), nodes.Value(i + 1).Z()]
                               for i in range(nodes.Size())], dtype=np.float32)
            faces_arr = np.array([[tris.Value(i + 1).Get()[j] - 1 for j in range(3)]
                                   for i in range(tris.Size())], dtype=np.int32) + offset
            all_verts.append(verts)
            all_faces.append(faces_arr)
            offset += len(verts)
        explorer.Next()

    if not all_verts:
        return np.zeros((0, 3), dtype=np.float32), np.zeros((0, 3), dtype=np.int32)

    return np.concatenate(all_verts), np.concatenate(all_faces)


def _synthetic_geometry(suffix: str, element_size: float = 5.0, file_path: Optional[Path] = None) -> GeometryData:
    """
    Fallback geometry processor for mock/demo mode.
    Attempts coordinates regex parsing for STEP files.
    Raises ValueError instead of returning a fake box if parsing cannot be done.
    """
    if suffix in (".step", ".stp"):
        if not file_path or not file_path.exists():
            raise ValueError(f"STEP file not found at path: {file_path}")
        
        try:
            import re
            from scipy.spatial import ConvexHull
            
            content = file_path.read_text(errors='ignore')
            pts = []
            # Robust regex pattern matching CARTESIAN_POINT with optional name in single quotes
            pattern = r"CARTESIAN_POINT\s*\(\s*(?:(?:'[^']*'|[^,]*)\s*,\s*)?\(\s*([^)]+)\s*\)\s*\)"
            for match in re.finditer(pattern, content, re.IGNORECASE):
                coord_str = match.group(1)
                parts = coord_str.split(',')
                if len(parts) == 3:
                    try:
                        x = float(parts[0].strip())
                        y = float(parts[1].strip())
                        z = float(parts[2].strip())
                        pts.append([x, y, z])
                    except ValueError:
                        continue
            
            if not pts:
                raise ValueError("No CARTESIAN_POINT definitions found in STEP file.")
                
            vertices = np.array(pts, dtype=np.float32)
            xmin, ymin, zmin = vertices.min(axis=0)
            xmax, ymax, zmax = vertices.max(axis=0)
            dx, dy, dz = float(xmax - xmin), float(ymax - ymin), float(zmax - zmin)
            
            dx = float(max(dx, 0.001))
            dy = float(max(dy, 0.001))
            dz = float(max(dz, 0.001))
            
            center_of_mass = (float((xmin + xmax) / 2), float((ymin + ymax) / 2), float((zmin + zmax) / 2))
            
            faces = []
            if len(vertices) >= 4:
                try:
                    hull = ConvexHull(vertices)
                    faces = hull.simplices.astype(np.int32)
                    volume = float(hull.volume)
                    surface_area = float(hull.area)
                except Exception as ex:
                    logger.warning("ConvexHull failed for fallback STEP points, using bounding box", error=str(ex))
                    faces = np.zeros((0, 3), dtype=np.int32)
                    volume = float(dx * dy * dz)
                    surface_area = float(2 * (dx * dy + dy * dz + dz * dx))
            else:
                faces = np.zeros((0, 3), dtype=np.int32)
                volume = float(dx * dy * dz)
                surface_area = float(2 * (dx * dy + dy * dz + dz * dx))
            
            logger.info(
                "Parsed STEP file coordinates using local ConvexHull fallback",
                num_vertices=len(vertices),
                num_faces=len(faces),
                bbox=(dx, dy, dz)
            )
            
            return GeometryData(
                volume=volume,
                surface_area=surface_area,
                bbox=(dx, dy, dz),
                center_of_mass=center_of_mass,
                vertices=vertices,
                faces=faces,
                is_watertight=True,
                num_components=1,
                format=suffix.lstrip("."),
            )
        except Exception as e:
            logger.error("Failed fallback step parsing", error=str(e), exc_info=True)
            raise ValueError(f"STEP parsing failed: {e}")
    elif suffix in (".iges", ".igs"):
        if not file_path or not file_path.exists():
            raise ValueError(f"IGES file not found at path: {file_path}")
        
        try:
            from scipy.spatial import ConvexHull
            content = file_path.read_text(errors='ignore')
            lines = content.splitlines()
            p_lines = []
            for line in lines:
                # Standard IGES: column 73 is 'P'
                if len(line) >= 73 and line[72] == 'P':
                    p_lines.append(line[:64])
            
            p_content = "".join(p_lines)
            entities = p_content.split(";")
            
            pts = []
            
            def parse_float(s):
                s = s.strip().replace('D', 'e').replace('d', 'e')
                return float(s)
                
            for ent in entities:
                ent = ent.strip()
                if not ent:
                    continue
                parts = [p.strip() for p in ent.split(",")]
                if not parts or not parts[0]:
                    continue
                
                try:
                    etype = int(parts[0])
                except ValueError:
                    continue
                    
                if etype == 502:  # Vertex List
                    try:
                        num_vertices = int(parts[1])
                        for i in range(num_vertices):
                            idx = 2 + i * 3
                            if idx + 2 < len(parts):
                                pts.append([
                                    parse_float(parts[idx]),
                                    parse_float(parts[idx+1]),
                                    parse_float(parts[idx+2])
                                ])
                    except Exception:
                        pass
                elif etype == 116:  # Point
                    try:
                        pts.append([
                            parse_float(parts[1]),
                            parse_float(parts[2]),
                            parse_float(parts[3])
                        ])
                    except Exception:
                        pass
                elif etype == 110:  # Line
                    try:
                        pts.append([
                            parse_float(parts[1]),
                            parse_float(parts[2]),
                            parse_float(parts[3])
                        ])
                        pts.append([
                            parse_float(parts[4]),
                            parse_float(parts[5]),
                            parse_float(parts[6])
                        ])
                    except Exception:
                        pass
                elif etype == 106:  # Copious Data
                    try:
                        ip = int(parts[1])
                        n = int(parts[2])
                        if ip in (1, 3):
                            stride = 6 if ip == 3 else 3
                            for i in range(n):
                                idx = 3 + i * stride
                                if idx + 2 < len(parts):
                                    pts.append([
                                        parse_float(parts[idx]),
                                        parse_float(parts[idx+1]),
                                        parse_float(parts[idx+2])
                                    ])
                        elif ip == 2:
                            zt = parse_float(parts[3])
                            for i in range(n):
                                idx = 4 + i * 2
                                if idx + 1 < len(parts):
                                    pts.append([
                                        parse_float(parts[idx]),
                                        parse_float(parts[idx+1]),
                                        zt
                                    ])
                    except Exception:
                        pass
                        
            # Fallback if no structured points found: extract any group of 3 consecutive floats in the parameter section
            if len(pts) < 4:
                all_tokens = []
                for ent in entities:
                    ent = ent.strip()
                    if not ent:
                        continue
                    tokens = [t.strip().replace('D', 'e').replace('d', 'e') for t in ent.split(',')]
                    for t in tokens:
                        try:
                            val = float(t)
                            if not val.is_integer() or abs(val) > 10:
                                all_tokens.append(val)
                        except ValueError:
                            pass
                
                for i in range(0, len(all_tokens) - 2, 3):
                    pts.append([all_tokens[i], all_tokens[i+1], all_tokens[i+2]])
            
            if not pts:
                raise ValueError("No coordinate points could be extracted from the IGES file.")
                
            vertices = np.array(pts, dtype=np.float32)
            xmin, ymin, zmin = vertices.min(axis=0)
            xmax, ymax, zmax = vertices.max(axis=0)
            dx, dy, dz = float(xmax - xmin), float(ymax - ymin), float(zmax - zmin)
            
            dx = float(max(dx, 0.001))
            dy = float(max(dy, 0.001))
            dz = float(max(dz, 0.001))
            
            center_of_mass = (float((xmin + xmax) / 2), float((ymin + ymax) / 2), float((zmin + zmax) / 2))
            
            faces = []
            if len(vertices) >= 4:
                try:
                    hull = ConvexHull(vertices)
                    faces = hull.simplices.astype(np.int32)
                    volume = float(hull.volume)
                    surface_area = float(hull.area)
                except Exception as ex:
                    logger.warning("ConvexHull failed for fallback IGES points, using bounding box", error=str(ex))
                    faces = np.zeros((0, 3), dtype=np.int32)
                    volume = float(dx * dy * dz)
                    surface_area = float(2 * (dx * dy + dy * dz + dz * dx))
            else:
                faces = np.zeros((0, 3), dtype=np.int32)
                volume = float(dx * dy * dz)
                surface_area = float(2 * (dx * dy + dy * dz + dz * dx))
                
            logger.info(
                "Parsed IGES file coordinates using local ConvexHull fallback",
                num_vertices=len(vertices),
                num_faces=len(faces),
                bbox=(dx, dy, dz)
            )
            
            return GeometryData(
                volume=volume,
                surface_area=surface_area,
                bbox=(dx, dy, dz),
                center_of_mass=center_of_mass,
                vertices=vertices,
                faces=faces,
                is_watertight=True,
                num_components=1,
                format=suffix.lstrip("."),
            )
        except Exception as e:
            logger.error("Failed fallback iges parsing", error=str(e), exc_info=True)
            raise ValueError(f"IGES parsing failed: {e}")
    else:
        # Reject other formats when real parsers fail
        raise ValueError(f"{suffix.upper().lstrip('.')} parsing is not supported in local fallback mode (requires OpenCASCADE / pythonocc-core).")

