"""Thermal solver — CalculiX HEAT TRANSFER step wrapper with mock mode."""
from __future__ import annotations
import asyncio
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional
from pathlib import Path
import numpy as np
import structlog
from app.config import settings

logger = structlog.get_logger(__name__)


@dataclass
class ThermalResult:
    max_temperature: float = 0.0
    min_temperature: float = 20.0
    temperature_field: np.ndarray = None
    heat_flux_field: np.ndarray = None
    result_data: Dict = None

    def __post_init__(self):
        if self.result_data is None:
            self.result_data = {}

    def to_dict(self):
        return {
            "max_temperature_c": round(self.max_temperature, 2),
            "min_temperature_c": round(self.min_temperature, 2),
        }


async def run_thermal(
    job_id: str,
    mesh_file: Optional[Path],
    parameters: Dict[str, Any],
    progress_callback: Optional[Callable] = None,
) -> ThermalResult:
    """Run steady-state or transient CalculiX thermal analysis."""
    import shutil
    if settings.mock_solver_mode or not shutil.which(settings.ccx_binary):
        if not settings.mock_solver_mode:
            await _report_thermal(progress_callback, 5, "WARNING: CalculiX binary 'ccx' not found on system path.")
            await _report_thermal(progress_callback, 10, "Falling back to emulation solver mode...")
        return await _mock_thermal(parameters, progress_callback, mesh_file)

    if not mesh_file:
        raise ValueError("Mesh file required for physical thermal analysis")

    workspace = settings.solver_workspace / job_id
    workspace.mkdir(parents=True, exist_ok=True)

    await _report_thermal(progress_callback, 10, "Generating thermal input deck…")
    inp_file = workspace / "thermal.inp"
    _write_thermal_inp(inp_file, mesh_file, parameters)

    await _report_thermal(progress_callback, 30, "Running CalculiX HEAT TRANSFER…")
    from app.solvers.structural.calculix_wrapper import _run_ccx
    await _run_ccx(inp_file, workspace, progress_callback)

    await _report_thermal(progress_callback, 85, "Parsing thermal results…")
    result = _parse_thermal_frd(workspace / "thermal.frd", parameters)

    await _report_thermal(progress_callback, 100, "Thermal analysis complete")
    return result


def _write_thermal_inp(
    inp_file: Path,
    mesh_file: Path,
    params: Dict[str, Any],
) -> None:
    """Generate a CalculiX .inp file for steady-state or transient thermal analysis."""
    mat = params.get("material", {})
    k   = mat.get("thermal_conductivity", 50.0)      # W/(m·K)
    cp  = mat.get("specific_heat", 490.0)             # J/(kg·K)
    rho = mat.get("density", 7850.0) * 1e-12          # kg/m³ → kg/mm³

    bcs = params.get("boundary_conditions", [])
    steady = params.get("steady_state", True)
    time_period = params.get("time_period", 1.0)
    steps = params.get("num_time_steps", 10)
    init_temp = params.get("initial_temperature", 20.0)

    lines = [
        f"** CalculiX Thermal — Job generated by CAD-CAE Analyzer",
        f"** Material: {mat.get('name', 'Unknown')}",
        f"*INCLUDE, INPUT={mesh_file}",
        f"",
        f"** Material definition",
        f"*MATERIAL, NAME=MAT",
        f"*CONDUCTIVITY",
        f"{k}",
        f"*SPECIFIC HEAT",
        f"{cp}",
        f"*DENSITY",
        f"{rho}",
        f"",
        f"** Section assignment",
        f"*SOLID SECTION, ELSET=EALL, MATERIAL=MAT",
    ]

    if not steady:
        lines += [
            f"",
            f"** Initial temperature",
            f"*INITIAL CONDITIONS, TYPE=TEMPERATURE",
            f"  EALL, {init_temp}",
        ]

    lines += [
        f"",
        f"** Step configuration",
        f"*STEP",
    ]

    if steady:
        lines.append(f"*HEAT TRANSFER, STEADY STATE")
    else:
        dt = time_period / steps
        lines.append(f"*HEAT TRANSFER")
        lines.append(f"  {dt}, {time_period}, {dt * 0.1}, {dt}")

    for bc in bcs:
        bc_type = bc.get("type", "")
        if bc_type == "fixed_temperature":
            node_set = _face_ids_to_nset_thermal(bc.get("face_ids", []))
            temp_val = bc.get("temperature", 100.0)
            lines += [
                f"*NSET, NSET=TEMP_{bc.get('description','BC')}",
                f"  {node_set}",
                f"*BOUNDARY",
                f"  TEMP_{bc.get('description','BC')}, 11, 11, {temp_val}",
            ]
        elif bc_type == "heat_flux":
            node_set = _face_ids_to_nset_thermal(bc.get("face_ids", []))
            flux = bc.get("flux", 1000.0)
            lines += [
                f"*NSET, NSET=FLUX_{bc.get('description','BC')}",
                f"  {node_set}",
                f"*DFLUX",
                f"  FLUX_{bc.get('description','BC')}, S, {flux}",
            ]
        elif bc_type == "convection":
            node_set = _face_ids_to_nset_thermal(bc.get("face_ids", []))
            hc = bc.get("film_coefficient", 25.0)
            amb = bc.get("ambient_temperature", 25.0)
            lines += [
                f"*NSET, NSET=CONV_{bc.get('description','BC')}",
                f"  {node_set}",
                f"*FILM",
                f"  CONV_{bc.get('description','BC')}, F, {amb}, {hc}",
            ]

    lines += [
        f"*NODE FILE",
        f"  NT",
        f"*END STEP",
    ]

    inp_file.write_text("\n".join(lines))


def _face_ids_to_nset_thermal(face_ids: List[int]) -> str:
    if not face_ids:
        return "1, LAST"
    return ", ".join(str(f) for f in face_ids[:20])


def _parse_thermal_frd(frd_file: Path, params: Dict[str, Any]) -> ThermalResult:
    """Parse CalculiX .frd result file for temperature field."""
    result = ThermalResult()
    if not frd_file.exists():
        raise FileNotFoundError(f"FRD file not found: {frd_file}")

    try:
        import meshio
        mesh = meshio.read(str(frd_file))

        if "NT" in mesh.point_data:
            temps = mesh.point_data["NT"]
            temps_flat = temps.flatten()
            result.max_temperature = float(temps_flat.max())
            result.min_temperature = float(temps_flat.min())
            result.temperature_field = temps_flat.astype(np.float32)

        result.result_data = result.to_dict()
    except Exception as e:
        logger.error("FRD thermal parsing failed", error=str(e))
        raise

    return result


async def _report_thermal(callback: Optional[Callable], pct: int, msg: str) -> None:
    if callback:
        if asyncio.iscoroutinefunction(callback):
            await callback(pct, msg)
        else:
            callback(pct, msg)


async def _mock_thermal(
    params: Dict,
    cb: Optional[Callable],
    mesh_file: Optional[Path] = None,
) -> ThermalResult:
    steady = params.get("steady_state", True)

    stages = [
        (15, "Setting up transient thermal mesh…"),
        (30, "Solving load step 1: t=0.1s…"),
        (50, "Solving load step 2: t=0.5s…"),
        (70, "Solving load step 3: t=0.8s…"),
        (85, "Converging temperature distribution at t=1.0s…"),
        (95, "Extracting nodal temperatures…"),
        (100, "Thermal transient analysis complete [OK]")
    ] if not steady else [
        (20, "Setting up thermal model..."),
        (50, "Assembling conductance matrix..."),
        (75, "Solving temperature field..."),
        (100, "Thermal analysis complete [OK]")
    ]
    for pct, msg in stages:
        await _report_thermal(cb, pct, msg)
        await asyncio.sleep(0.5)

    bcs = params.get("boundary_conditions", [])
    conv = next((b for b in bcs if b.get("type") == "convection"), {})
    ambient = conv.get("ambient_temperature", 25.0)
    h = conv.get("film_coefficient", 10.0)  # W/(m²·K)

    # Physics-based estimate: T_surface = T_ambient + Q / (h * A)
    # Assume a small body with 10 W internal heat dissipation and A=0.01 m²
    Q = 10.0   # watts (assumed internal heat generation)
    A = 0.01   # m² (reference convective area)
    delta_T = Q / (h * A)  # °C rise above ambient
    max_temp = round(ambient + delta_T, 2)
    min_temp_surface = round(ambient + delta_T * 0.3, 2)  # far from heat source

    if not steady:
        # Transient: temperature has not yet reached steady-state
        init_temp = params.get("initial_temperature", 20.0)
        # Simulate 78% of the way to steady-state
        max_temp = round(init_temp + (max_temp - init_temp) * 0.78, 2)
        min_temp_surface = round(init_temp + (min_temp_surface - init_temp) * 0.78, 2)

    # ── Vertex-level thermal calculations over N frames ──
    vertex_count = 500
    vertices = None
    if mesh_file and Path(mesh_file).exists():
        try:
            import trimesh
            mesh = trimesh.load(str(mesh_file), force="mesh")
            vertices = mesh.vertices
            vertex_count = len(vertices)
        except Exception:
            pass

    if vertices is None:
        xs = np.linspace(0, 100, vertex_count)
        vertices = np.column_stack([xs, np.zeros(vertex_count), np.zeros(vertex_count)])

    xmin = float(vertices[:, 0].min())
    xmax = float(vertices[:, 0].max())
    L = max(xmax - xmin, 0.001)

    frames = []
    num_frames = 10
    
    for t_idx in range(num_frames):
        t = t_idx / (num_frames - 1)
        
        f_temps = []
        for v in vertices:
            x_val = v[0]
            factor = (x_val - xmin) / L
            temp_rise = delta_T * np.exp(-3 * factor)
            
            if not steady:
                temp_rise = temp_rise * (1.0 - np.exp(-3 * (t + 0.1)))
            else:
                temp_rise = temp_rise * t
                
            temp = ambient + temp_rise
            f_temps.append(float(temp))
            
        frames.append({
            "frame_index": t_idx,
            "time": t,
            "displacement": np.zeros((vertex_count, 3)).tolist(),
            "temperature": f_temps
        })

    r = ThermalResult(
        max_temperature=round(float(np.max(frames[-1]["temperature"])), 2),
        min_temperature=round(float(np.min(frames[-1]["temperature"])), 2),
        temperature_field=np.array(frames[-1]["temperature"], dtype=np.float32),
    )
    r.result_data = {
        **r.to_dict(),
        "frames": frames
    }
    return r
