"""Thermal solver — CalculiX HEAT TRANSFER step wrapper with mock mode."""
from __future__ import annotations
import asyncio
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional
from pathlib import Path
import numpy as np
import structlog
from app.config import settings

logger = structlog.get_logger(__name__)


@dataclass
class ThermalResult:
    max_temperature: float = 0.0
    min_temperature: float = 20.0
    temperature_field: np.ndarray = None
    heat_flux_field: np.ndarray = None
    result_data: Dict = None

    def __post_init__(self):
        if self.result_data is None:
            self.result_data = {}

    def to_dict(self):
        return {
            "max_temperature_c": round(self.max_temperature, 2),
            "min_temperature_c": round(self.min_temperature, 2),
        }


async def run_thermal(
    job_id: str,
    mesh_file: Optional[Path],
    parameters: Dict[str, Any],
    progress_callback: Optional[Callable] = None,
) -> ThermalResult:
    """Run steady-state or transient CalculiX thermal analysis."""
    if settings.mock_solver_mode:
        return await _mock_thermal(parameters, progress_callback)

    if not mesh_file:
        raise ValueError("Mesh file required for physical thermal analysis")

    workspace = settings.solver_workspace / job_id
    workspace.mkdir(parents=True, exist_ok=True)

    await _report_thermal(progress_callback, 10, "Generating thermal input deck…")
    inp_file = workspace / "thermal.inp"
    _write_thermal_inp(inp_file, mesh_file, parameters)

    await _report_thermal(progress_callback, 30, "Running CalculiX HEAT TRANSFER…")
    from app.solvers.structural.calculix_wrapper import _run_ccx
    await _run_ccx(inp_file, workspace, progress_callback)

    await _report_thermal(progress_callback, 85, "Parsing thermal results…")
    result = _parse_thermal_frd(workspace / "thermal.frd", parameters)

    await _report_thermal(progress_callback, 100, "Thermal analysis complete")
    return result


def _write_thermal_inp(
    inp_file: Path,
    mesh_file: Path,
    params: Dict[str, Any],
) -> None:
    """Generate a CalculiX .inp file for steady-state or transient thermal analysis."""
    mat = params.get("material", {})
    k   = mat.get("thermal_conductivity", 50.0)      # W/(m·K)
    cp  = mat.get("specific_heat", 490.0)             # J/(kg·K)
    rho = mat.get("density", 7850.0) * 1e-12          # kg/m³ → kg/mm³

    bcs = params.get("boundary_conditions", [])
    steady = params.get("steady_state", True)
    time_period = params.get("time_period", 1.0)
    steps = params.get("num_time_steps", 10)
    init_temp = params.get("initial_temperature", 20.0)

    lines = [
        f"** CalculiX Thermal — Job generated by CAD-CAE Analyzer",
        f"** Material: {mat.get('name', 'Unknown')}",
        f"*INCLUDE, INPUT={mesh_file}",
        f"",
        f"** Material definition",
        f"*MATERIAL, NAME=MAT",
        f"*CONDUCTIVITY",
        f"{k}",
        f"*SPECIFIC HEAT",
        f"{cp}",
        f"*DENSITY",
        f"{rho}",
        f"",
        f"** Section assignment",
        f"*SOLID SECTION, ELSET=EALL, MATERIAL=MAT",
    ]

    if not steady:
        lines += [
            f"",
            f"** Initial temperature",
            f"*INITIAL CONDITIONS, TYPE=TEMPERATURE",
            f"  EALL, {init_temp}",
        ]

    lines += [
        f"",
        f"** Step configuration",
        f"*STEP",
    ]

    if steady:
        lines.append(f"*HEAT TRANSFER, STEADY STATE")
    else:
        dt = time_period / steps
        lines.append(f"*HEAT TRANSFER")
        lines.append(f"  {dt}, {time_period}, {dt * 0.1}, {dt}")

    for bc in bcs:
        bc_type = bc.get("type", "")
        if bc_type == "fixed_temperature":
            node_set = _face_ids_to_nset_thermal(bc.get("face_ids", []))
            temp_val = bc.get("temperature", 100.0)
            lines += [
                f"*NSET, NSET=TEMP_{bc.get('description','BC')}",
                f"  {node_set}",
                f"*BOUNDARY",
                f"  TEMP_{bc.get('description','BC')}, 11, 11, {temp_val}",
            ]
        elif bc_type == "heat_flux":
            node_set = _face_ids_to_nset_thermal(bc.get("face_ids", []))
            flux = bc.get("flux", 1000.0)
            lines += [
                f"*NSET, NSET=FLUX_{bc.get('description','BC')}",
                f"  {node_set}",
                f"*DFLUX",
                f"  FLUX_{bc.get('description','BC')}, S, {flux}",
            ]
        elif bc_type == "convection":
            node_set = _face_ids_to_nset_thermal(bc.get("face_ids", []))
            hc = bc.get("film_coefficient", 25.0)
            amb = bc.get("ambient_temperature", 25.0)
            lines += [
                f"*NSET, NSET=CONV_{bc.get('description','BC')}",
                f"  {node_set}",
                f"*FILM",
                f"  CONV_{bc.get('description','BC')}, F, {amb}, {hc}",
            ]

    lines += [
        f"*NODE FILE",
        f"  NT",
        f"*END STEP",
    ]

    inp_file.write_text("\n".join(lines))


def _face_ids_to_nset_thermal(face_ids: List[int]) -> str:
    if not face_ids:
        return "1, LAST"
    return ", ".join(str(f) for f in face_ids[:20])


def _parse_thermal_frd(frd_file: Path, params: Dict[str, Any]) -> ThermalResult:
    """Parse CalculiX .frd result file for temperature field."""
    result = ThermalResult()
    if not frd_file.exists():
        raise FileNotFoundError(f"FRD file not found: {frd_file}")

    try:
        import meshio
        mesh = meshio.read(str(frd_file))

        if "NT" in mesh.point_data:
            temps = mesh.point_data["NT"]
            temps_flat = temps.flatten()
            result.max_temperature = float(temps_flat.max())
            result.min_temperature = float(temps_flat.min())
            result.temperature_field = temps_flat.astype(np.float32)

        result.result_data = result.to_dict()
    except Exception as e:
        logger.error("FRD thermal parsing failed", error=str(e))
        raise

    return result


async def _report_thermal(callback: Optional[Callable], pct: int, msg: str) -> None:
    if callback:
        if asyncio.iscoroutinefunction(callback):
            await callback(pct, msg)
        else:
            callback(pct, msg)


async def _mock_thermal(params: Dict, cb: Optional[Callable]) -> ThermalResult:
    steady = params.get("steady_state", True)

    stages = [
        (15, "Setting up transient thermal mesh…"),
        (30, "Solving load step 1: t=0.1s…"),
        (50, "Solving load step 2: t=0.5s…"),
        (70, "Solving load step 3: t=0.8s…"),
        (85, "Converging temperature distribution at t=1.0s…"),
        (95, "Extracting nodal temperatures…"),
        (100, "Thermal transient analysis complete ✓")
    ] if not steady else [
        (20, "Setting up thermal model…"),
        (50, "Assembling conductance matrix…"),
        (75, "Solving temperature field…"),
        (100, "Thermal analysis complete ✓")
    ]
    for pct, msg in stages:
        await _report_thermal(cb, pct, msg)
        await asyncio.sleep(0.5)

    bcs = params.get("boundary_conditions", [])
    conv = next((b for b in bcs if b.get("type") == "convection"), {})
    ambient = conv.get("ambient_temperature", 25.0)
    heat = conv.get("film_coefficient", 10.0)
    max_temp = ambient + 1000 / (heat * 0.01)

    if not steady:
        init_temp = params.get("initial_temperature", 20.0)
        max_temp = init_temp + (max_temp - init_temp) * 0.78

    n = 80
    x = np.linspace(0, 1, n)
    temp_field = (max_temp - ambient) * np.exp(-3 * x) + ambient

    r = ThermalResult(max_temperature=round(float(temp_field.max()), 2),
                      min_temperature=round(float(temp_field.min()), 2),
                      temperature_field=temp_field.astype(np.float32))
    r.result_data = r.to_dict()
    return r
